export const NEXT_STATUS = {
  APPLIED: "SCREENING",
  SCREENING: "SHORTLISTED",
  SHORTLISTED: "INTERVIEW_SCHEDULED",
  INTERVIEW_SCHEDULED: "TECHNICAL_ROUND",
  TECHNICAL_ROUND: "HR_ROUND",
  HR_ROUND: "SELECTED"
};




